var pathwayId = 113; 
var searchedText = '';
var markerName = '';
var searchedFoodText = '';
var relation;
var autoCompleteList = [];
var _svgObject;
var _svgGroup;
var _svgRect;
var _svgText;
var firstLayer = 'Layer_x0020_1';
var groupPrefix = 'grp_';
var harmfulPrefix = 'hrm_';
var beneficialPrefix = 'bft_';
var sectionPrefix = 'sec_';
var startPrefix = 'str_';
var endPrefix = 'end_';
var textCount = 0;
var currentIndex = 0;
var gTagArray = [];
var startList = [];
var endList = [];
var markerList = [];
var arrResearchURL = [];
var txtSearch = $('#txtSearch');
var txtSearchFood = $('#txtSearchFood');
var txtPID = $('#txtPID');
var lblCount = $('#lblCount');
var ddlSection = $('#ddlSection');
var ddlSubSection = $('#ddlSubSection');
var colorPicker = $('#colorPicker');
var ddlLead = $('#ddlLead');
var markerURLList = [];
var frontMarkerURLList = [];
